name: draftmode_worker
description: Lightweight timed worker for Flutter. Runs a short background task with duration and progress callbacks.
publish_to: "none"
version: 1.0.0+1
homepage: https://draftmode.io/dev/flutter/worker
license: MIT

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: "3.35.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: TimedWorkerPlugin
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
#  draftmode_ui:
#    path: ../ui
#    git: https://github.com/draftm0de/flutter.ui
#    version: ^1.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

repository: https://github.com/draftm0de/flutter.worker
issue_tracker: https://github.com/draftm0de/flutter.worker/issues
