name: draftmode_worker
description: Lightweight timed worker for Flutter. Runs a short background task with duration and progress callbacks.
version: 0.1.0
homepage: https://draftmode.io/dev/flutter/worker
license: MIT

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: TimedWorkerPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

repository: https://github.com/draftm0de/flutter.worker
issue_tracking: https://github.com/draftm0de/flutter.worker/issues